---
title: Running Google Earth Engine from Python
author: Jillian Deines
date: '2017-11-03'
slug: python-for-gee
draft: yes
categories: []
tags:
  - EarthEngine, python
---

pretty decent conda tutorial from Don/Geohackweek: https://geohackweek.github.io/Introductory/01-conda-tutorial/

* Install anaconda/python if you have not.
  * Basics: install via Anaconda, as described in this [DataCamp article](https://www.datacamp.com/community/tutorials/installing-anaconda-mac-os-x). you only ever need 1 version of Anaconda installed
  * check to see if you need to update Conda: `$ conda update -n base conda`
  * the Earth Engine API uses Python 2.6 or 2.7 (?), so either choose Anaconda for 2.7, or go ahead and get Anaconda with 3.6 (or whatever is now the most recent) and subsequently use that version of Anaconda to install 2.7
* Install 2.7
  * in terminal, create a python 2.7 environment: `$ conda create -n py27 python=2.7`
  * activate the `py27` environment just created: `$ source activate py27`
    * note I think this would just be `$ activate py27` for Windows
  * side note: to see all environments on your system: `$ conda info --envs` or `$ conda env list`; the activated environment is starred *
  
  
## A note on conda environments
conda environments specify a set of packages to be used in 1 or more projects. you can create new environments by using an environment file (YAML format, xyz.yml) or by manually specifying packages.

Its good practice to use projectenviro.yml files so it's all there an reproducible. An example, which would be in a text file with extension environment.yml and would load a python 3.6 environment along with the package 'pyjokes' via pip install:

```{r eval=FALSE}
name: testenv
channels:
- conda-forge
dependencies:
- python=3.6
- pip
- pip:
    - pyjokes
```

You would then install this environment.yml file to create a conda environment called 'testenv':

```
$ conda env create --file environment.yml
```

## Get setup with GEE

terminal, python 2.7:

1. install Google APIs client library

```
pip install google-api-python-client
```

2. check that the functioning crypto libraries are installed:

```
python -c "from oauth2client import crypt"
```

If you get an error, install a Crypto library:

```{}
pip install PyCrypto
```

install the earth engine python api

```{}
pip install earthengine-api
```

I still got an error message from `python -c "from oauth2client import crypt"` so I then also explicitly installed oauth2client (I had been working in a fresh environment I recently created)

```{}
pip install oauth2client
python -c "from oauth2client import crypt"
```

set up authentication credentials

```{}
python -c "import ee; ee.Initialize()"

# and when prompted, possibly in a new terminal window but I didn't read that first
# and it seems fine to run in the same terminal...
earthengine authenticate
```

Running this command opens a web browser window where you login with your google account and authenticate, finally copying an authentication and pasting it back into the command prompt

Should receive a message "successfully saved authorization token"

## Test it



in future:
* open terminal
* activate environment `source activate py27` where py27 is the environment name
* (1x) `conda install spyder`
* `spyder`
*

Then run

```{}
# Import the Earth Engine Python Package
import ee

# Initialize the Earth Engine object, using the authentication credentials.
ee.Initialize()

# Print the information for an image asset.
image = ee.Image('srtm90_v4')
print(image.getInfo())
```

and if everything is correct, the metadata for an image should be printed

## going further
That was pretty bare bones. Let's assume I want more packages in my environment

* open terminal
* activate environment: `source activate py27`
* list existing packages in environment: `conda list -n py27`

There's a lot there but not some of what I anticipate needing. I think I can use `conda install` and `pip install` interchangably here, except in cases where something isn't on conda and I need to use pip.

```{}
# one at a time
conda install numpy 

# or many at once
conda install scipy pandas gdal matplotlib geopandas rasterio
```

### installing packages not on conda
George Azzari's `gee_tools` package is (hosted on Github)[https://github.com/george-azzari/gee_tools] and not found via conda install or pip install.

So, I can tell it to install from git:

```{}
pip install git+git://github.com/george-azzari/gee_tools.git
```

Seems good!

# test gee_tools
See if I can run something. Using Spyder here for no good reason at all, except I read the internet about Spyder vs PyCharm and decided both seem to have their advantages, and thus far I've actually used Spyder before.

To do this from the beginning:

* open the terminal
* activate python environment: `source activate py27`
* launch spyder, which I've already installed in this environment above: `spyder`

The rest will be the script run in Spyder:

```{}

```


